use axum::{
    Router,
    extract::DefaultBodyLimit,
    routing::{delete, get, post},
};

use crate::api;
use common::state::AppState;

pub(super) fn ai_routes() -> Router<AppState> {
    Router::new()
        .route(
            "/ai/agents",
            get(api::ai_agents::get_ai_agents).post(api::ai_agents::create_ai_agent),
        )
        .route(
            "/ai/agents/{agent_id}",
            get(api::ai_agents::get_ai_agent_by_id)
                .patch(api::ai_agents::update_ai_agent)
                .delete(api::ai_agents::delete_ai_agent),
        )
        .route(
            "/ai/agents/{agent_id}/details",
            get(api::ai_agents::get_ai_agent_details),
        )
        .route(
            "/ai/agents/{agent_id}/skills",
            post(api::ai_skills::import_agent_skill_bundle)
                .delete(api::ai_skills::delete_agent_skill_path)
                .layer(DefaultBodyLimit::max(25 * 1024 * 1024)),
        )
        .route(
            "/ai/agents/{agent_id}/skills/tree",
            get(api::ai_skills::list_skill_tree),
        )
        .route(
            "/ai/agents/{agent_id}/skills/file",
            get(api::ai_skills::read_skill_file),
        )
        .route(
            "/ai/agents/{agent_id}/sub-agents",
            get(api::ai_agents::get_agent_sub_agents),
        )
        .route(
            "/ai/agents/{agent_id}/sub-agents/{sub_agent_id}",
            post(api::ai_agents::attach_sub_agent_to_agent)
                .delete(api::ai_agents::detach_sub_agent_from_agent),
        )
        .route(
            "/ai/tools",
            get(api::ai_tools::get_ai_tools).post(api::ai_tools::create_ai_tool),
        )
        .route(
            "/ai/tools/{tool_id}",
            get(api::ai_tools::get_ai_tool_by_id)
                .patch(api::ai_tools::update_ai_tool)
                .delete(api::ai_tools::delete_ai_tool),
        )
        .route(
            "/ai/agents/{agent_id}/tools",
            get(api::ai_tools::get_agent_tools),
        )
        .route(
            "/ai/agents/{agent_id}/tools/{tool_id}",
            post(api::ai_tools::attach_tool_to_agent).delete(api::ai_tools::detach_tool_from_agent),
        )
        .route(
            "/ai/knowledge-bases",
            get(api::ai_knowledge_base::get_ai_knowledge_bases)
                .post(api::ai_knowledge_base::create_ai_knowledge_base),
        )
        .route(
            "/ai/knowledge-bases/{kb_id}",
            get(api::ai_knowledge_base::get_ai_knowledge_base_by_id)
                .patch(api::ai_knowledge_base::update_ai_knowledge_base)
                .delete(api::ai_knowledge_base::delete_ai_knowledge_base),
        )
        .route(
            "/ai/knowledge-bases/{kb_id}/documents",
            get(api::ai_knowledge_base::get_knowledge_base_documents)
                .post(api::ai_knowledge_base::upload_knowledge_base_document)
                .layer(DefaultBodyLimit::max(25 * 1024 * 1024)),
        )
        .route(
            "/ai/knowledge-bases/{kb_id}/documents/{document_id}",
            delete(api::ai_knowledge_base::delete_knowledge_base_document),
        )
        .route(
            "/ai/mcp-servers",
            get(api::mcp_servers::get_mcp_servers).post(api::mcp_servers::create_mcp_server),
        )
        .route(
            "/ai/mcp-servers/discover",
            post(api::mcp_servers::discover_mcp_server_auth),
        )
        .route(
            "/ai/mcp-servers/{mcp_server_id}",
            get(api::mcp_servers::get_mcp_server_by_id)
                .patch(api::mcp_servers::update_mcp_server)
                .delete(api::mcp_servers::delete_mcp_server),
        )
        .route(
            "/ai/agents/{agent_id}/knowledge-bases",
            get(api::ai_knowledge_base::get_agent_knowledge_bases),
        )
        .route(
            "/ai/agents/{agent_id}/knowledge-bases/{kb_id}",
            post(api::ai_knowledge_base::attach_knowledge_base_to_agent)
                .delete(api::ai_knowledge_base::detach_knowledge_base_from_agent),
        )
        .route(
            "/ai/settings",
            get(api::ai_settings::get_ai_settings).put(api::ai_settings::update_ai_settings),
        )
}
