//! OIDC: insert a freshly-generated RSA signing key for an OAuth app.
//! Key material is generated by the caller (platform crate — owns the `rsa`
//! dependency); this command only persists it.

use common::error::AppError;

pub struct InsertOAuthAppSigningKey {
    pub id: i64,
    pub oauth_app_id: i64,
    pub kid: String,
    pub algorithm: String,
    pub public_key_pem: String,
    pub private_key_pem: String,
}

pub struct OAuthAppSigningKeyInserted {
    /// `true` when this insert won the race for the (oauth_app_id, active)
    /// slot; `false` when a concurrent insert beat us (caller should re-read).
    pub inserted: bool,
}

impl InsertOAuthAppSigningKey {
    pub async fn execute_with_db<'e, E>(
        self,
        executor: E,
    ) -> Result<OAuthAppSigningKeyInserted, AppError>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let res = sqlx::query!(
            r#"
            INSERT INTO oauth_app_signing_keys (
                id, oauth_app_id, kid, algorithm, public_key_pem, private_key_pem,
                status, activated_at, created_at
            ) VALUES ($1, $2, $3, $4, $5, $6, 'active', NOW(), NOW())
            ON CONFLICT (oauth_app_id) WHERE status = 'active' DO NOTHING
            "#,
            self.id,
            self.oauth_app_id,
            self.kid,
            self.algorithm,
            self.public_key_pem,
            self.private_key_pem,
        )
        .execute(executor)
        .await?;

        Ok(OAuthAppSigningKeyInserted {
            inserted: res.rows_affected() > 0,
        })
    }
}

/// Atomic key rotation: flips the current `active` row to `retired` (keeps
/// publishing it in JWKS so in-flight id_tokens still verify) and inserts the
/// caller-supplied new key as the next `active`. Caller is responsible for
/// generating the RSA keypair (platform crate owns the `rsa` dep).
pub struct RotateOAuthAppSigningKey {
    pub oauth_app_id: i64,
    pub new_id: i64,
    pub new_kid: String,
    pub new_algorithm: String,
    pub new_public_key_pem: String,
    pub new_private_key_pem: String,
}

pub struct OAuthAppSigningKeyRotated {
    pub new_kid: String,
    pub retired_kid: Option<String>,
}

impl RotateOAuthAppSigningKey {
    pub async fn execute_with_pool(
        self,
        pool: &sqlx::PgPool,
    ) -> Result<OAuthAppSigningKeyRotated, AppError> {
        let mut tx = pool.begin().await?;

        // 1) Retire the current active key (if any). Returns its kid for
        //    audit logging.
        let retired = sqlx::query!(
            r#"
            UPDATE oauth_app_signing_keys
               SET status = 'retired', retired_at = NOW()
             WHERE oauth_app_id = $1
               AND status = 'active'
             RETURNING kid
            "#,
            self.oauth_app_id,
        )
        .fetch_optional(&mut *tx)
        .await?;

        // 2) Insert the freshly-generated key as the new active.
        sqlx::query!(
            r#"
            INSERT INTO oauth_app_signing_keys (
                id, oauth_app_id, kid, algorithm, public_key_pem, private_key_pem,
                status, activated_at, created_at
            ) VALUES ($1, $2, $3, $4, $5, $6, 'active', NOW(), NOW())
            "#,
            self.new_id,
            self.oauth_app_id,
            self.new_kid,
            self.new_algorithm,
            self.new_public_key_pem,
            self.new_private_key_pem,
        )
        .execute(&mut *tx)
        .await?;

        tx.commit().await?;

        Ok(OAuthAppSigningKeyRotated {
            new_kid: self.new_kid,
            retired_kid: retired.map(|r| r.kid),
        })
    }
}

/// Mark a key as `compromised`. Compromised keys are excluded from JWKS,
/// which hard-breaks verification of any in-flight token they signed —
/// that's the point. Operators trigger this when they suspect a leak.
pub struct CompromiseOAuthAppSigningKey {
    pub oauth_app_id: i64,
    pub kid: String,
}

impl CompromiseOAuthAppSigningKey {
    pub async fn execute_with_db<'e, E>(self, executor: E) -> Result<bool, AppError>
    where
        E: sqlx::Executor<'e, Database = sqlx::Postgres>,
    {
        let res = sqlx::query!(
            r#"
            UPDATE oauth_app_signing_keys
               SET status = 'compromised', retired_at = NOW()
             WHERE oauth_app_id = $1
               AND kid = $2
               AND status <> 'compromised'
            "#,
            self.oauth_app_id,
            self.kid,
        )
        .execute(executor)
        .await?;
        Ok(res.rows_affected() > 0)
    }
}
