use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let skills_root = manifest.join("skills/system");
    println!("cargo:rerun-if-changed={}", skills_root.display());

    let mut entries: Vec<SkillEntry> = Vec::new();
    if skills_root.is_dir() {
        for dir_entry in fs::read_dir(&skills_root).expect("read skills/system") {
            let dir_entry = dir_entry.expect("dir entry");
            let path = dir_entry.path();
            if !path.is_dir() {
                continue;
            }
            let slug = match path.file_name().and_then(|s| s.to_str()) {
                Some(s) => s.to_string(),
                None => continue,
            };
            let skill_md = path.join("SKILL.md");
            if !skill_md.exists() {
                continue;
            }
            println!("cargo:rerun-if-changed={}", skill_md.display());
            let content = fs::read_to_string(&skill_md).expect("read SKILL.md");
            let (name, description) = parse_frontmatter(&content);
            entries.push(SkillEntry {
                slug: slug.clone(),
                name: name.unwrap_or(slug),
                description,
                skill_md: content,
            });
        }
    }

    entries.sort_by(|a, b| a.slug.cmp(&b.slug));

    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("system_skills_data.rs");
    let mut generated = String::from(
        "// auto-generated by build.rs — do not edit\n\
         pub(crate) struct GeneratedSkill { pub slug: &'static str, pub name: &'static str, pub description: &'static str, pub skill_md: &'static str }\n\
         pub(crate) static GENERATED_SYSTEM_SKILLS: &[GeneratedSkill] = &[\n",
    );
    for entry in &entries {
        generated.push_str(&format!(
            "    GeneratedSkill {{ slug: {slug}, name: {name}, description: {desc}, skill_md: {md} }},\n",
            slug = rust_string(&entry.slug),
            name = rust_string(&entry.name),
            desc = rust_string(entry.description.as_deref().unwrap_or("")),
            md = rust_string(&entry.skill_md),
        ));
    }
    generated.push_str("];\n");
    fs::write(&out_path, generated).expect("write generated system skills");
}

struct SkillEntry {
    slug: String,
    name: String,
    description: Option<String>,
    skill_md: String,
}

fn parse_frontmatter(content: &str) -> (Option<String>, Option<String>) {
    let mut lines = content.lines();
    if lines.next().map(|l| l.trim()) != Some("---") {
        return (None, None);
    }
    let mut name = None;
    let mut description = None;
    for line in lines {
        let trimmed = line.trim_end();
        if trimmed.trim() == "---" {
            break;
        }
        if let Some(rest) = trimmed.strip_prefix("name:") {
            name = Some(rest.trim().to_string());
        } else if let Some(rest) = trimmed.strip_prefix("description:") {
            description = Some(rest.trim().to_string());
        }
    }
    (name, description)
}

fn rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
