use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone)]
pub struct EmailTemplate {
    pub template_name: String,
    pub template_data: String,
    pub template_from: String,
    pub template_reply_to: String,
    pub template_subject: String,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct DeploymentEmailTemplate {
    pub id: i64,
    pub deployment_id: i64,
    pub organization_invite_template: EmailTemplate,
    pub verification_code_template: EmailTemplate,
    pub reset_password_code_template: EmailTemplate,
    pub primary_email_change_template: EmailTemplate,
    pub password_change_template: EmailTemplate,
    pub password_remove_template: EmailTemplate,
    pub sign_in_from_new_device_template: EmailTemplate,
    pub magic_link_template: EmailTemplate,
    pub waitlist_signup_template: EmailTemplate,
    pub waitlist_invite_template: EmailTemplate,
    pub workspace_invite_template: EmailTemplate,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl Default for DeploymentEmailTemplate {
    fn default() -> Self {
        Self {
            id: 0,
            deployment_id: 0,
            organization_invite_template: EmailTemplate {
                template_name: "Organization Invitation".to_string(),
                template_from: "invitations".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "{{inviter_name}} invited you to join {{organization_name}} on {{app.name}}".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.border-color{border-color:#333333!important}.text-primary{color:#ffffff!important}.text-secondary{color:#a0a0a0!important}.text-tertiary{color:#808080!important}.btn{background-color:#ffffff!important;color:#000000!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">You've been invited to {{organization_name}}</h1><p class="text-secondary" style="margin:0 0 24px 0;font-size:15px;line-height:24px;color:#666666">{{inviter_name}} has invited you to join {{organization_name}} on {{app.name}}.</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:0 0 24px 0"><a href="{{action_url}}" class="btn" style="display:inline-block;padding:14px 32px;background-color:#000000;color:#ffffff;text-decoration:none;font-size:15px;font-weight:400;border-radius:4px">Accept Invitation</a></td></tr></table><p class="text-tertiary" style="margin:0 0 16px 0;font-size:13px;line-height:20px;color:#999999">This invitation will expire in {{invitation.expires_in_days}} days.</p><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">Or copy and paste this URL into your browser:<br><a href="{{action_url}}" class="text-secondary" style="color:#666666;word-break:break-all">{{action_url}}</a></p></td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">If you weren't expecting this invitation, you can safely ignore this email.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            verification_code_template: EmailTemplate {
                template_name: "Verification Code".to_string(),
                template_from: "verification".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "{{code.value}} is your verification code for {{app.name}}".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.bg-code{background-color:#2a2a2a!important}.border-color{border-color:#333333!important}.text-primary{color:#ffffff!important}.text-secondary{color:#a0a0a0!important}.text-tertiary{color:#808080!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">Verification Code</h1><p class="text-secondary" style="margin:0 0 32px 0;font-size:15px;line-height:24px;color:#666666">Use the following code to verify your identity:</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td class="bg-code border-color" style="background-color:#f8f8f8;border:2px solid #e5e5e5;padding:24px;text-align:center"><span class="text-primary" style="font-size:28px;font-weight:400;letter-spacing:8px;color:#000000;font-family:'Courier New',monospace">{{code.value}}</span></td></tr></table><p class="text-tertiary" style="margin:24px 0 0 0;font-size:13px;line-height:20px;color:#999999">This code will expire in {{code.expires_in_minutes}} minutes.</p>{{#if device.info}}<table width="100%" cellpadding="0" cellspacing="0" style="margin:24px 0 0 0"><tr><td class="bg-info border-color" style="background-color:#f8f8f8;padding:16px;border:1px solid #e5e5e5"><p class="text-primary" style="margin:0 0 8px 0;font-size:13px;font-weight:400;color:#000000">Device Information:</p><p class="text-secondary" style="margin:0;font-size:13px;line-height:20px;color:#666666">{{device.info}}</p></td></tr></table>{{/if}}</td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">If you didn't request this code, you can safely ignore this email.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            reset_password_code_template: EmailTemplate {
                template_name: "Reset Password Code".to_string(),
                template_from: "security".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "Reset your password for {{app.name}}".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.bg-code{background-color:#2a2a2a!important}.border-color{border-color:#333333!important}.text-primary{color:#ffffff!important}.text-secondary{color:#a0a0a0!important}.text-tertiary{color:#808080!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">Reset Your Password</h1><p class="text-secondary" style="margin:0 0 32px 0;font-size:15px;line-height:24px;color:#666666">Use the following code to reset your password:</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td class="bg-code border-color" style="background-color:#f8f8f8;border:2px solid #e5e5e5;padding:24px;text-align:center"><span class="text-primary" style="font-size:28px;font-weight:400;letter-spacing:8px;color:#000000;font-family:'Courier New',monospace">{{code.value}}</span></td></tr></table><p class="text-tertiary" style="margin:24px 0 0 0;font-size:13px;line-height:20px;color:#999999">This code will expire in {{code.expires_in_minutes}} minutes.</p>{{#if device_info}}<table width="100%" cellpadding="0" cellspacing="0" style="margin:24px 0 0 0"><tr><td class="bg-info border-color" style="background-color:#f8f8f8;padding:16px;border:1px solid #e5e5e5"><p class="text-primary" style="margin:0 0 8px 0;font-size:13px;font-weight:400;color:#000000">Device Information:</p><p class="text-secondary" style="margin:0;font-size:13px;line-height:20px;color:#666666">{{device.info}}</p></td></tr></table>{{/if}}</td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">If you didn't request a password reset, you can safely ignore this email.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            primary_email_change_template: EmailTemplate {
                template_name: "Email Address Changed".to_string(),
                template_from: "security".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "Your primary email address was changed on {{app.name}}".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.bg-alert{background-color:#0a0a0a!important}.border-color{border-color:#333333!important}.border-alert{border-left-color:#ffffff!important}.text-primary{color:#ffffff!important}.text-secondary{color:#b3b3b3!important}.text-tertiary{color:#666666!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">Email Address Changed</h1><p class="text-secondary" style="margin:0 0 24px 0;font-size:15px;line-height:24px;color:#666666">The primary email address for your {{app.name}} account was recently updated.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px 0"><tr><td class="bg-alert border-color border-alert" style="background-color:#f8f8f8;border-left:3px solid #000000;padding:16px"><p class="text-secondary" style="margin:0;font-size:13px;line-height:20px;color:#666666">If you didn't make this change, please contact support immediately.</p></td></tr></table></td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">This is an automated security notification.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            password_change_template: EmailTemplate {
                template_name: "Password Changed".to_string(),
                template_from: "security".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "Your password was changed on {{app.name}}".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.bg-alert{background-color:#0a0a0a!important}.border-color{border-color:#333333!important}.border-alert{border-left-color:#ffffff!important}.text-primary{color:#ffffff!important}.text-secondary{color:#b3b3b3!important}.text-tertiary{color:#666666!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">Password Changed</h1><p class="text-secondary" style="margin:0 0 24px 0;font-size:15px;line-height:24px;color:#666666">Your {{app.name}} account password was successfully changed.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px 0"><tr><td class="bg-alert border-color border-alert" style="background-color:#f8f8f8;border-left:3px solid #000000;padding:16px"><p class="text-secondary" style="margin:0;font-size:13px;line-height:20px;color:#666666">If you didn't make this change, please reset your password immediately and contact support.</p></td></tr></table></td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">This is an automated security notification.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            password_remove_template: EmailTemplate {
                template_name: "Password Removed".to_string(),
                template_from: "security".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "Your password was removed from your {{app.name}} account".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.bg-alert{background-color:#0a0a0a!important}.border-color{border-color:#333333!important}.border-alert{border-left-color:#ffffff!important}.text-primary{color:#ffffff!important}.text-secondary{color:#b3b3b3!important}.text-tertiary{color:#666666!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">Password Removed</h1><p class="text-secondary" style="margin:0 0 24px 0;font-size:15px;line-height:24px;color:#666666">The password for your {{app.name}} account has been removed. You'll need to use alternative sign-in methods.</p><table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px 0"><tr><td class="bg-alert border-color border-alert" style="background-color:#f8f8f8;border-left:3px solid #000000;padding:16px"><p class="text-secondary" style="margin:0;font-size:13px;line-height:20px;color:#666666">If you didn't make this change, please contact support immediately.</p></td></tr></table></td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">This is an automated security notification.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            sign_in_from_new_device_template: EmailTemplate {
                template_name: "New Device Sign In".to_string(),
                template_from: "security".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "Sign in from a new device detected on {{app.name}}".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.bg-info{background-color:#0a0a0a!important}.bg-alert{background-color:#0a0a0a!important}.border-color{border-color:#333333!important}.border-alert{border-left-color:#ffffff!important}.text-primary{color:#ffffff!important}.text-secondary{color:#b3b3b3!important}.text-tertiary{color:#666666!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">New Device Sign-In Detected</h1><p class="text-secondary" style="margin:0 0 24px 0;font-size:15px;line-height:24px;color:#666666">We detected a sign-in to your {{app.name}} account from a new device or location.</p>{{#if device_info}}<table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px 0"><tr><td class="bg-info border-color" style="background-color:#f8f8f8;padding:16px;border:1px solid #e5e5e5"><p class="text-primary" style="margin:0 0 8px 0;font-size:13px;font-weight:400;color:#000000">Device Information:</p><p class="text-secondary" style="margin:0;font-size:13px;line-height:20px;color:#666666">{{device.info}}</p></td></tr></table>{{/if}}<table width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 24px 0"><tr><td class="bg-alert border-color border-alert" style="background-color:#f8f8f8;border-left:3px solid #000000;padding:16px"><p class="text-secondary" style="margin:0;font-size:13px;line-height:20px;color:#666666">If this wasn't you, please secure your account immediately by resetting your password.</p></td></tr></table></td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">This is an automated security notification.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            magic_link_template: EmailTemplate {
                template_name: "Magic Link Sign In".to_string(),
                template_from: "authentication".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "Sign in to {{app.name}}".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.border-color{border-color:#333333!important}.text-primary{color:#ffffff!important}.text-secondary{color:#b3b3b3!important}.text-tertiary{color:#666666!important}.btn{background-color:#ffffff!important;color:#000000!important}.link{color:#999999!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">Sign In</h1><p class="text-secondary" style="margin:0 0 32px 0;font-size:15px;line-height:24px;color:#666666">Click the button below to sign in to your account.</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:0 0 24px 0"><a href="{{action_url}}" class="btn" style="display:inline-block;padding:14px 32px;background-color:#000000;color:#ffffff;text-decoration:none;font-size:15px;font-weight:400;border-radius:4px">Sign In</a></td></tr></table><p class="text-tertiary" style="margin:0 0 16px 0;font-size:13px;line-height:20px;color:#999999">This link will expire in {{link.expires_in_minutes}} minutes.</p><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">Or copy and paste this URL into your browser:<br><a href="{{action_url}}" class="link" style="color:#666666;word-break:break-all">{{action_url}}</a></p></td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">If you didn't request this link, you can safely ignore this email.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            waitlist_signup_template: EmailTemplate {
                template_name: "Added to Waitlist".to_string(),
                template_from: "notifications".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "You're on the waitlist for {{app.name}}".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.border-color{border-color:#333333!important}.text-primary{color:#ffffff!important}.text-secondary{color:#b3b3b3!important}.text-tertiary{color:#666666!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">You're on the Waitlist</h1><p class="text-secondary" style="margin:0 0 24px 0;font-size:15px;line-height:24px;color:#666666">Thank you for your interest in {{app.name}}. You've been successfully added to our waitlist.</p><p class="text-secondary" style="margin:0;font-size:15px;line-height:24px;color:#666666">We'll notify you as soon as a spot becomes available.</p></td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">Thank you for your patience.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            waitlist_invite_template: EmailTemplate {
                template_name: "Waitlist Invitation".to_string(),
                template_from: "invitations".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "You're invited to join {{app.name}} from the waitlist!".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.border-color{border-color:#333333!important}.text-primary{color:#ffffff!important}.text-secondary{color:#b3b3b3!important}.text-tertiary{color:#666666!important}.btn{background-color:#ffffff!important;color:#000000!important}.link{color:#999999!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">Your Invitation is Ready</h1><p class="text-secondary" style="margin:0 0 24px 0;font-size:15px;line-height:24px;color:#666666">You've been invited to join {{app.name}} from the waitlist. Click the button below to get started.</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:0 0 24px 0"><a href="{{action_url}}" class="btn" style="display:inline-block;padding:14px 32px;background-color:#000000;color:#ffffff;text-decoration:none;font-size:15px;font-weight:400;border-radius:4px">Get Started</a></td></tr></table><p class="text-tertiary" style="margin:0 0 16px 0;font-size:13px;line-height:20px;color:#999999">This invitation will expire in {{invitation.expires_in_days}} days.</p><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">Or copy and paste this URL into your browser:<br><a href="{{action_url}}" class="link" style="color:#666666;word-break:break-all">{{action_url}}</a></p></td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">We're excited to have you join us.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            workspace_invite_template: EmailTemplate {
                template_name: "Invitation".to_string(),
                template_from: "invitations".to_string(),
                template_reply_to: "".to_string(),
                template_subject: "Invitation to join {{app.name}}".to_string(),
                template_data: r#"<!DOCTYPE html><html><head><meta name="color-scheme" content="light dark"><meta name="supported-color-schemes" content="light dark"><style>:root{color-scheme:light dark;supported-color-schemes:light dark}@media (prefers-color-scheme:dark){.bg-outer{background-color:#000000!important}.bg-main{background-color:#1a1a1a!important}.bg-footer{background-color:#0a0a0a!important}.border-color{border-color:#333333!important}.text-primary{color:#ffffff!important}.text-secondary{color:#b3b3b3!important}.text-tertiary{color:#666666!important}.btn{background-color:#ffffff!important;color:#000000!important}.link{color:#999999!important}}</style></head><body style="margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif"><div class="bg-outer" style="background-color:#ffffff"><table width="100%" cellpadding="0" cellspacing="0" class="bg-outer" style="background-color:#f5f5f5;padding:40px 0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" class="bg-main border-color" style="background-color:#ffffff;border:1px solid #e5e5e5"><tr><td class="border-color" style="padding:20px 48px;text-align:center;border-bottom:1px solid #e5e5e5">{{image app.logo}}</td></tr><tr><td style="padding:24px 48px"><h1 class="text-primary" style="margin:0 0 16px 0;font-size:20px;font-weight:400;color:#000000;line-height:1.3">You've Been Invited</h1><p class="text-secondary" style="margin:0 0 24px 0;font-size:15px;line-height:24px;color:#666666">{{#if inviter_name}}{{escapeURIs inviter_name}} has invited you to join them on {{app.name}}.{{else}}You are invited to join {{app.name}}.{{/if}}</p><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:0 0 24px 0"><a href="{{action_url}}" class="btn" style="display:inline-block;padding:14px 32px;background-color:#000000;color:#ffffff;text-decoration:none;font-size:15px;font-weight:400;border-radius:4px">Accept Invitation</a></td></tr></table><p class="text-tertiary" style="margin:0 0 16px 0;font-size:13px;line-height:20px;color:#999999">This invitation will expire in {{invitation.expires_in_days}} days.</p><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">Or copy and paste this URL into your browser:<br><a href="{{action_url}}" class="link" style="color:#666666;word-break:break-all">{{action_url}}</a></p></td></tr><tr><td class="bg-footer border-color" style="padding:20px 48px;background-color:#f8f8f8;border-top:1px solid #e5e5e5"><p class="text-tertiary" style="margin:0;font-size:13px;line-height:20px;color:#999999">If you weren't expecting this invitation, you can safely ignore this email.</p></td></tr></table></td></tr></table></div></body></html>"#.to_string(),
            },
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }
}
