use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Default)]
pub struct TokenOverrides {
    pub space_unit: Option<String>,
    pub card: Option<String>,
    pub card_foreground: Option<String>,
    pub popover: Option<String>,
    pub popover_foreground: Option<String>,
    pub primary_foreground: Option<String>,
    pub secondary: Option<String>,
    pub secondary_foreground: Option<String>,
    pub accent: Option<String>,
    pub accent_foreground: Option<String>,
    pub ring: Option<String>,
    pub foreground: Option<String>,
    pub foreground_inverse: Option<String>,
    pub secondary_text: Option<String>,
    pub muted: Option<String>,
    pub border: Option<String>,
    pub border_hover: Option<String>,
    pub divider: Option<String>,
    pub input_background: Option<String>,
    pub input_border: Option<String>,
    pub input_focus_border: Option<String>,
    pub background_subtle: Option<String>,
    pub background_hover: Option<String>,
    pub primary_hover: Option<String>,
    pub error: Option<String>,
    pub error_background: Option<String>,
    pub error_border: Option<String>,
    pub warning: Option<String>,
    pub warning_background: Option<String>,
    pub warning_border: Option<String>,
    pub warning_text: Option<String>,
    pub success: Option<String>,
    pub success_background: Option<String>,
    pub success_border: Option<String>,
    pub info: Option<String>,
    pub info_background: Option<String>,
    pub radius_md: Option<String>,
    pub radius_lg: Option<String>,
    pub radius_xl: Option<String>,
    pub radius_2xl: Option<String>,
    pub radius_2xs: Option<String>,
    pub radius_xs: Option<String>,
    pub radius_full: Option<String>,
    pub border_width_thin: Option<String>,
    pub border_width_regular: Option<String>,
    pub scrollbar_track: Option<String>,
    pub scrollbar_thumb: Option<String>,
    pub scrollbar_thumb_hover: Option<String>,
    pub shadow_color: Option<String>,
    pub shadow_light_color: Option<String>,
    pub shadow_medium_color: Option<String>,
    pub success_shadow: Option<String>,
    pub success_background_light: Option<String>,
    pub button_ripple: Option<String>,
    pub dialog_backdrop: Option<String>,
    pub space_0u: Option<String>,
    pub space_1u: Option<String>,
    pub space_2u: Option<String>,
    pub space_3u: Option<String>,
    pub space_4u: Option<String>,
    pub space_5u: Option<String>,
    pub space_6u: Option<String>,
    pub space_7u: Option<String>,
    pub space_8u: Option<String>,
    pub space_10u: Option<String>,
    pub space_12u: Option<String>,
    pub space_14u: Option<String>,
    pub space_16u: Option<String>,
    pub space_24u: Option<String>,
    pub font_size_2xs: Option<String>,
    pub font_size_xs: Option<String>,
    pub font_size_sm: Option<String>,
    pub font_size_md: Option<String>,
    pub font_size_lg: Option<String>,
    pub font_size_xl: Option<String>,
    pub font_size_2xl: Option<String>,
    pub font_size_3xl: Option<String>,
    pub size_8u: Option<String>,
    pub size_10u: Option<String>,
    pub size_12u: Option<String>,
    pub size_18u: Option<String>,
    pub size_20u: Option<String>,
    pub size_24u: Option<String>,
    pub size_32u: Option<String>,
    pub size_36u: Option<String>,
    pub size_40u: Option<String>,
    pub size_45u: Option<String>,
    pub size_50u: Option<String>,
    pub shadow_sm: Option<String>,
    pub shadow_md: Option<String>,
    pub shadow_lg: Option<String>,
    pub shadow_xl: Option<String>,
    pub shadow_success: Option<String>,
    pub ring_primary: Option<String>,
    pub letter_spacing_tight: Option<String>,
}

fn default_light_mode_token_overrides() -> TokenOverrides {
    TokenOverrides {
        card: Some("oklch(1 0 0)".to_string()),
        card_foreground: Some("oklch(0.145 0 0)".to_string()),
        popover: Some("oklch(1 0 0)".to_string()),
        popover_foreground: Some("oklch(0.145 0 0)".to_string()),
        primary_foreground: Some("oklch(0.985 0 0)".to_string()),
        secondary: Some("oklch(0.97 0 0)".to_string()),
        secondary_foreground: Some("oklch(0.205 0 0)".to_string()),
        accent: Some("oklch(0.97 0 0)".to_string()),
        accent_foreground: Some("oklch(0.205 0 0)".to_string()),
        ring: Some("oklch(0.708 0 0)".to_string()),
        foreground: Some("oklch(0.145 0 0)".to_string()),
        secondary_text: Some("oklch(0.556 0 0)".to_string()),
        muted: Some("oklch(0.556 0 0)".to_string()),
        border: Some("oklch(0.922 0 0)".to_string()),
        border_hover: Some("oklch(0.922 0 0)".to_string()),
        divider: Some("oklch(0.922 0 0)".to_string()),
        input_background: Some("oklch(1 0 0)".to_string()),
        input_border: Some("oklch(0.922 0 0)".to_string()),
        input_focus_border: Some("oklch(0.708 0 0)".to_string()),
        background_subtle: Some("oklch(0.97 0 0)".to_string()),
        background_hover: Some("oklch(0.97 0 0)".to_string()),
        primary_hover: Some("oklch(0.205 0 0)".to_string()),
        error: Some("#EF4444".to_string()),
        error_background: Some("rgba(239, 68, 68, 0.1)".to_string()),
        error_border: Some("rgba(239, 68, 68, 0.2)".to_string()),
        warning: Some("#854D0E".to_string()),
        warning_background: Some("#FEF9C3".to_string()),
        warning_border: Some("#FEF08A".to_string()),
        warning_text: Some("#92400E".to_string()),
        success: Some("#166534".to_string()),
        success_background: Some("#DCFCE7".to_string()),
        success_border: Some("rgba(34, 197, 94, 0.3)".to_string()),
        info: Some("#3B82F6".to_string()),
        info_background: Some("#DBEAFE".to_string()),
        ..default_shared_token_overrides()
    }
}

fn default_shared_token_overrides() -> TokenOverrides {
    TokenOverrides {
        space_unit: Some("2px".to_string()),
        radius_2xs: Some("4px".to_string()),
        radius_xs: Some("6px".to_string()),
        radius_md: Some("8px".to_string()),
        radius_lg: Some("12px".to_string()),
        radius_xl: Some("16px".to_string()),
        radius_2xl: Some("20px".to_string()),
        radius_full: Some("9999px".to_string()),
        border_width_thin: Some("0.5px".to_string()),
        border_width_regular: Some("2px".to_string()),
        space_0u: Some("0px".to_string()),
        space_1u: Some("2px".to_string()),
        space_2u: Some("4px".to_string()),
        space_3u: Some("6px".to_string()),
        space_4u: Some("8px".to_string()),
        space_5u: Some("10px".to_string()),
        space_6u: Some("12px".to_string()),
        space_7u: Some("14px".to_string()),
        space_8u: Some("16px".to_string()),
        space_10u: Some("20px".to_string()),
        space_12u: Some("24px".to_string()),
        space_14u: Some("28px".to_string()),
        space_16u: Some("32px".to_string()),
        space_24u: Some("48px".to_string()),
        font_size_2xs: Some("10px".to_string()),
        font_size_xs: Some("11px".to_string()),
        font_size_sm: Some("12px".to_string()),
        font_size_md: Some("13px".to_string()),
        font_size_lg: Some("14px".to_string()),
        font_size_xl: Some("16px".to_string()),
        font_size_2xl: Some("18px".to_string()),
        font_size_3xl: Some("20px".to_string()),
        size_8u: Some("16px".to_string()),
        size_10u: Some("20px".to_string()),
        size_12u: Some("24px".to_string()),
        size_18u: Some("36px".to_string()),
        size_20u: Some("40px".to_string()),
        size_24u: Some("48px".to_string()),
        size_32u: Some("64px".to_string()),
        size_36u: Some("72px".to_string()),
        size_40u: Some("80px".to_string()),
        size_45u: Some("90px".to_string()),
        size_50u: Some("100px".to_string()),
        shadow_sm: Some("0 1px 2px var(--color-shadow-light)".to_string()),
        shadow_md: Some("0 2px 8px var(--color-shadow)".to_string()),
        shadow_lg: Some("0 8px 24px var(--color-shadow)".to_string()),
        shadow_xl: Some("0 16px 40px var(--color-shadow-medium)".to_string()),
        ring_primary: Some(
            "0 0 0 3px color-mix(in srgb, var(--color-ring) 35%, transparent)".to_string(),
        ),
        letter_spacing_tight: Some("0.5px".to_string()),
        ..Default::default()
    }
}

fn default_dark_mode_token_overrides() -> TokenOverrides {
    TokenOverrides {
        card: Some("oklch(0.24 0 0)".to_string()),
        card_foreground: Some("oklch(0.985 0 0)".to_string()),
        popover: Some("oklch(0.24 0 0)".to_string()),
        popover_foreground: Some("oklch(0.985 0 0)".to_string()),
        primary_foreground: Some("oklch(0.205 0 0)".to_string()),
        secondary: Some("oklch(0.28 0 0)".to_string()),
        secondary_foreground: Some("oklch(0.985 0 0)".to_string()),
        accent: Some("oklch(0.371 0 0)".to_string()),
        accent_foreground: Some("oklch(0.985 0 0)".to_string()),
        ring: Some("oklch(0.556 0 0)".to_string()),
        foreground: Some("oklch(0.985 0 0)".to_string()),
        secondary_text: Some("oklch(0.708 0 0)".to_string()),
        muted: Some("oklch(0.708 0 0)".to_string()),
        border: Some("oklch(1 0 0 / 10%)".to_string()),
        border_hover: Some("oklch(1 0 0 / 15%)".to_string()),
        divider: Some("oklch(1 0 0 / 10%)".to_string()),
        input_background: Some("oklch(0.24 0 0)".to_string()),
        input_border: Some("oklch(1 0 0 / 15%)".to_string()),
        input_focus_border: Some("oklch(0.556 0 0)".to_string()),
        background_subtle: Some("oklch(0.24 0 0)".to_string()),
        background_hover: Some("oklch(0.28 0 0)".to_string()),
        primary_hover: Some("oklch(0.87 0 0)".to_string()),
        error: Some("#F87171".to_string()),
        error_background: Some("rgba(248, 113, 113, 0.1)".to_string()),
        error_border: Some("rgba(248, 113, 113, 0.3)".to_string()),
        warning: Some("#FBBF24".to_string()),
        warning_background: Some("rgba(251, 191, 36, 0.1)".to_string()),
        warning_border: Some("rgba(251, 191, 36, 0.3)".to_string()),
        warning_text: Some("#FBBF24".to_string()),
        success: Some("#22C55E".to_string()),
        success_background: Some("rgba(34, 197, 94, 0.1)".to_string()),
        success_border: Some("rgba(34, 197, 94, 0.3)".to_string()),
        info: Some("#60A5FA".to_string()),
        info_background: Some("rgba(96, 165, 250, 0.1)".to_string()),
        ..default_shared_token_overrides()
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub struct LightModeSettings {
    pub primary_color: Option<String>,
    pub background_color: Option<String>,
    pub text_color: Option<String>,
    #[serde(default)]
    pub token_overrides: Option<TokenOverrides>,
}

impl Default for LightModeSettings {
    fn default() -> Self {
        Self {
            primary_color: Some("oklch(0.205 0 0)".to_string()),
            background_color: Some("oklch(1 0 0)".to_string()),
            text_color: Some("oklch(0.145 0 0)".to_string()),
            token_overrides: Some(default_light_mode_token_overrides()),
        }
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub struct DarkModeSettings {
    pub primary_color: Option<String>,
    pub background_color: Option<String>,
    pub text_color: Option<String>,
    #[serde(default)]
    pub token_overrides: Option<TokenOverrides>,
}

impl Default for DarkModeSettings {
    fn default() -> Self {
        Self {
            primary_color: Some("oklch(0.87 0 0)".to_string()),
            background_color: Some("oklch(0.205 0 0)".to_string()),
            text_color: Some("oklch(0.985 0 0)".to_string()),
            token_overrides: Some(default_dark_mode_token_overrides()),
        }
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub struct DeploymentUISettings {
    #[serde(with = "crate::utils::serde::i64_as_string")]
    pub id: i64,
    pub created_at: Option<DateTime<Utc>>,
    pub updated_at: Option<DateTime<Utc>>,
    #[serde(with = "crate::utils::serde::i64_as_string")]
    pub deployment_id: i64,
    pub app_name: String,
    pub tos_page_url: String,
    pub sign_in_page_url: String,
    pub sign_up_page_url: String,
    pub after_sign_out_one_page_url: String,
    pub after_sign_out_all_page_url: String,
    pub favicon_image_url: String,
    pub logo_image_url: String,
    pub privacy_policy_url: String,
    pub signup_terms_statement: String,
    pub signup_terms_statement_shown: bool,
    pub light_mode_settings: LightModeSettings,
    pub dark_mode_settings: DarkModeSettings,
    pub after_logo_click_url: String,
    pub organization_profile_url: String,
    pub create_organization_url: String,
    pub default_user_profile_image_url: String,
    pub default_organization_profile_image_url: String,
    pub default_workspace_profile_image_url: String,
    pub use_initials_for_user_profile_image: bool,
    pub use_initials_for_organization_profile_image: bool,
    pub after_signup_redirect_url: String,
    pub after_signin_redirect_url: String,
    pub user_profile_url: String,
    pub after_create_organization_redirect_url: String,
    pub waitlist_page_url: String,
    pub support_page_url: String,
}

impl Default for DeploymentUISettings {
    fn default() -> Self {
        Self {
            id: 0,
            created_at: None,
            updated_at: None,
            deployment_id: 0,
            app_name: "".to_string(),
            tos_page_url: "".to_string(),
            sign_in_page_url: "".to_string(),
            sign_up_page_url: "".to_string(),
            after_sign_out_one_page_url: "".to_string(),
            after_sign_out_all_page_url: "".to_string(),
            favicon_image_url: "".to_string(),
            logo_image_url: "".to_string(),
            privacy_policy_url: "".to_string(),
            signup_terms_statement: "I agree to the Terms of Service and Privacy Policy"
                .to_string(),
            signup_terms_statement_shown: true,
            light_mode_settings: LightModeSettings::default(),
            dark_mode_settings: DarkModeSettings::default(),
            after_logo_click_url: "".to_string(),
            organization_profile_url: "".to_string(),
            create_organization_url: "".to_string(),
            default_user_profile_image_url: "".to_string(),
            default_organization_profile_image_url: "".to_string(),
            default_workspace_profile_image_url: "".to_string(),
            use_initials_for_user_profile_image: true,
            use_initials_for_organization_profile_image: true,
            after_signup_redirect_url: "".to_string(),
            after_signin_redirect_url: "".to_string(),
            user_profile_url: "".to_string(),
            after_create_organization_redirect_url: "".to_string(),
            waitlist_page_url: "".to_string(),
            support_page_url: "".to_string(),
        }
    }
}
